### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by jihyunjeongme** [jihyunjeongme/python-restapi-minitwitter#1]
![image](https://user-images.githubusercontent.com/43984584/53322794-cbf34d00-391f-11e9-89c5-659144da8dfb.png)

![image](https://user-images.githubusercontent.com/43984584/53322810-d6154b80-391f-11e9-9527-8401a4fc54b2.png)

**Comment by jihyunjeongme** [comment]
timeline 엔드포인트

![image](https://user-images.githubusercontent.com/43984584/56072163-17c65c80-5dcf-11e9-829a-1615cfa04bef.png)

**Comment by jihyunjeongme** [comment]
Follow 기능

![image](https://user-images.githubusercontent.com/43984584/56072869-9a9ee580-5dd6-11e9-9126-28431735cf7d.png)

Unfollow 기능
![image](https://user-images.githubusercontent.com/43984584/56073127-61687480-5dda-11e9-8dde-49a7c6a479b3.png)

Sign up
![image](https://user-images.githubusercontent.com/43984584/56073149-a1c7f280-5dda-11e9-81b0-6a5605afb438.png)

**Comment by jihyunjeongme** [comment]
암호화 한 이후 Sign-up
![image](https://user-images.githubusercontent.com/43984584/56074883-810c9680-5df4-11e9-9973-53aa7de4c7a5.png)

아래와 같이 Hashed_password 값을 가짐
![image](https://user-images.githubusercontent.com/43984584/56074891-9aadde00-5df4-11e9-81fd-e7f08c7e4112.png)

토큰 값 가져오기(Login)
![image](https://user-images.githubusercontent.com/43984584/56075113-368d1900-5df8-11e9-83d9-542806c910e4.png)

토큰 값 가지고 Tweet 날리기
![image](https://user-images.githubusercontent.com/43984584/56075185-5f61de00-5df9-11e9-950c-4bb6fa1fb3e9.png)

잘 생성된 Tweet
![image](https://user-images.githubusercontent.com/43984584/56075212-e3b46100-5df9-11e9-8c3e-33a404a5ab6b.png)

정상적으로 작동되는거 확인
![image](https://user-images.githubusercontent.com/43984584/56076240-ace64700-5e09-11e9-847b-aa1cb14b8496.png)

**Comment by jihyunjeongme** [comment]
pytest 테스트 결과(tweet 테스트)

![image](https://user-images.githubusercontent.com/43984584/56078318-9c41cb00-5e21-11e9-851c-a6a46a298ed3.png)

**Comment by jihyunjeongme** [comment]
pytest 모듈을 통해 모든 기능 테스트 결과

![image](https://user-images.githubusercontent.com/43984584/56079330-e6c94480-5e2d-11e9-88c6-cb07c4c0747c.png)

**Comment by jihyunjeongme** [comment]
Amazon RDS 설정

![image](https://user-images.githubusercontent.com/43984584/56079496-6a843080-5e30-11e9-88f1-7ecdb1a00956.png)


EC2 새키 페어 생성

![image](https://user-images.githubusercontent.com/43984584/56086273-4e16e100-5e8e-11e9-83a6-087721153afb.png)

ssh -i /Users/jihyun/Documents/Non-business/9.\ AWS/python-restapi-backend/python-test.pem ubuntu@ec2-13-124-72-213.ap-northeast-2.compute.amazonaws.com


아래로 시도시 에러날 경우
![image](https://user-images.githubusercontent.com/43984584/56086388-73591e80-5e91-11e9-8113-6bad0157439c.png)

chmod 400 파일명.pem

다시 위 커맨드 시도하면 잘됨

![image](https://user-images.githubusercontent.com/43984584/56086399-9257b080-5e91-11e9-8b3d-0c1113665251.png)

**Comment by jihyunjeongme** [comment]
SHA256:12v6JYUYJAYLDAYWPs3XA/tJ47bN0ETiKPBN6DrMwbo jihyunjeongme@gmail.com

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyo4mrzAlQFfJuOx8rhTXEq1ZQ37e10PpcsAPSY4VsIVd8SA2wR+IFLmHJdSqHB6H5OTsCH1pjSxG4NMSVnqWkWhAxjcYG7CD+QfPhZa2SjmuWFusTFjBQ4n7DnPf9AgBrzygaMZuDSblIai8BNVxx6mlsqxZCON6Uta2KApwOkJPZtmLGpXC6QJNnuZKSXb8BtGG/gqrwBeQnB9CBgbyw6b5qf1+6q6w5wqnB7uwHcFeNr93JUX2VoO+q4abqwY66+N0UNQBQO44ueTZJHPmKqQge0Va6uvuXTcDNXyd+p8mnlGxEY+0Qc5OdxhVSrU20Y0nWOfP6sBvIfcTnZB0uMOfdx4xjFYtL/uCWGxZDIc84n5OyoyYJg+ioI/cyR3mdE68Boipis/gVMfczWROR/g45LDSY5/lPHk+ybn7VdFzmgqbr/xJ/ebxR98eM1/FpTQeGkyZtOW4uvt+3N/2N3EbbaeAgdsjI0jlAdRaDrZGTirSIbV1nY6vAPP+dbZYytcgWLft6SgT4TGQKGcm3lenHsqS0+a7pm1G+NKXTIT8SqkxQAJG+RRrSJWd6eibRneCOFgQJOBJmZJd1kmgX1uu7RRvO9+RCqBl83sGMsbxjzL0HXA9eRX0oBgGYQSAOEIc1/zRrRHuXzn6kE2qpw9x4lICdmZqbL27yJluEQQ== jihyunjeongme@gmail.com

![image](https://user-images.githubusercontent.com/43984584/56086646-48bd9480-5e96-11e9-8dab-9cf6f7fee628.png)


![image](https://user-images.githubusercontent.com/43984584/56086800-4d377c80-5e99-11e9-9e4d-ec83e78635d6.png)


![image](https://user-images.githubusercontent.com/43984584/56086816-84a62900-5e99-11e9-9f58-2aba9b033216.png)

AWS EC2에 미니콘다 다운로드

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
![image](https://user-images.githubusercontent.com/43984584/56086834-dcdd2b00-5e99-11e9-903c-73003865f959.png)


설치 및 Conda Parh에 추가
`해당 사이트 참고` : https://openmmtools.readthedocs.io/en/latest/installation.html

$ wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
$ bash ./Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/ubuntu/miniconda3
$ export PATH="$HOME/ubuntu/miniconda3/bin:$PATH"
![image](https://user-images.githubusercontent.com/43984584/56086892-0c406780-5e9b-11e9-888a-7b536fd2d907.png)

파이썬 가상환결 설정
conda create --name api python=3.7

![image](https://user-images.githubusercontent.com/43984584/56086904-47429b00-5e9b-11e9-92fa-558da4f560f4.png)

가상환경 실행 시킨 후 외부프레임 워크와 라이브러리들 설치
![image](https://user-images.githubusercontent.com/43984584/56086907-617c7900-5e9b-11e9-96e7-7e861db43457.png)

![image](https://user-images.githubusercontent.com/43984584/56086910-807b0b00-5e9b-11e9-8092-1f60c9a9b17c.png)

![image](https://user-images.githubusercontent.com/43984584/56086914-9ee10680-5e9b-11e9-9cf7-ebb3f99ff1cc.png)


 from mysql import connector
ModuleNotFoundError: No module named 'mysql' 에러 나는 경우

![image](https://user-images.githubusercontent.com/43984584/56087115-765b0b80-5e9f-11e9-9fd8-c352e7d91210.png)

![image](https://user-images.githubusercontent.com/43984584/56087123-8f63bc80-5e9f-11e9-9a59-5cb0e6754e31.png)

```bash 
$ pip search mysql-connector | grep --color mysql-connector-python
mysql-connector-python-rf (2.2.2)        - MySQL driver written in Python
mysql-connector-python (2.0.4)           - MySQL driver written in Python

Install the mysql-connector-python-rf -

$ pip install mysql-connector-python-rf
Verify

$ python
Python 2.7.11 (default, Apr 26 2016, 13:18:56)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mysql.connector
>>>

```
![image](https://user-images.githubusercontent.com/43984584/56087131-ad312180-5e9f-11e9-8e18-83ffbcbdf8f5.png)

아래와 같은 에러를 만날경우
![image](https://user-images.githubusercontent.com/43984584/56087266-495c2800-5ea2-11e9-8fd3-b13be373b6b9.png)

sudo apt-get update
sudo apt install gcc

성공적으 됨

**Comment by jihyunjeongme** [comment]
Mysql 접근 방법

mysql -h python-backend-test.cyk5jvszavwv.ap-northeast-2.rds.amazonaws.com -u root -p

자주쓰는 명령어
minoconda 활성: export PATH="$HOME/ubuntu/miniconda3/bin:$PATH"
서버 실행: nohup python setup.py runserver --host=0.0.0.0 &
실행되는 서버 확인: ps -ef | grep runserver
서버 죽이기: kill codenumber
로그확인: vi nohup.out
확인: curl localhost:5000/ping

성공!!
http -v POST "http://13.125.249.212:5000/sign-up" \
name="슈퍼맨"  \
email="super@gmail.com"  \
password="password_sample"  \
profile="Super Developer"


![image](https://user-images.githubusercontent.com/43984584/56088128-4c144880-5eb5-11e9-8140-441ce86f5406.png)

**Comment by jihyunjeongme** [comment]
## 순서

### 1. AWS instance 접속

ssh -i /Users/jihyun/Documents/Non-business/9.\ AWS/python-restapi-backend/python-test.pem ubuntu@ec2-13-209-35-14.ap-northeast-2.compute.amazonaws.com

### 1.1 Deployment key가 있다고 가정
SHA256:12v6JYUYJAYLDAYWPs3XA/tJ47bN0ETiKPBN6DrMwbo jihyunjeongme@gmail.com

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyo4mrzAlQFfJuOx8rhTXEq1ZQ37e10PpcsAPSY4VsIVd8SA2wR+IFLmHJdSqHB6H5OTsCH1pjSxG4NMSVnqWkWhAxjcYG7CD+QfPhZa2SjmuWFusTFjBQ4n7DnPf9AgBrzygaMZuDSblIai8BNVxx6mlsqxZCON6Uta2KApwOkJPZtmLGpXC6QJNnuZKSXb8BtGG/gqrwBeQnB9CBgbyw6b5qf1+6q6w5wqnB7uwHcFeNr93JUX2VoO+q4abqwY66+N0UNQBQO44ueTZJHPmKqQge0Va6uvuXTcDNXyd+p8mnlGxEY+0Qc5OdxhVSrU20Y0nWOfP6sBvIfcTnZB0uMOfdx4xjFYtL/uCWGxZDIc84n5OyoyYJg+ioI/cyR3mdE68Boipis/gVMfczWROR/g45LDSY5/lPHk+ybn7VdFzmgqbr/xJ/ebxR98eM1/FpTQeGkyZtOW4uvt+3N/2N3EbbaeAgdsjI0jlAdRaDrZGTirSIbV1nY6vAPP+dbZYytcgWLft6SgT4TGQKGcm3lenHsqS0+a7pm1G+NKXTIT8SqkxQAJG+RRrSJWd6eibRneCOFgQJOBJmZJd1kmgX1uu7RRvO9+RCqBl83sGMsbxjzL0HXA9eRX0oBgGYQSAOEIc1/zRrRHuXzn6kE2qpw9x4lICdmZqbL27yJluEQQ== jihyunjeongme@gmail.com

![image](https://user-images.githubusercontent.com/43984584/56086646-48bd9480-5e96-11e9-8dab-9cf6f7fee628.png)


![image](https://user-images.githubusercontent.com/43984584/56086800-4d377c80-5e99-11e9-9e4d-ec83e78635d6.png)


![image](https://user-images.githubusercontent.com/43984584/56086816-84a62900-5e99-11e9-9f58-2aba9b033216.png)



### 2. Git glone
```bash
git clone https://github.com/jihyunjeongme/python-miniter-aws.git
Cloning into 'python-miniter-aws'...
Username for 'https://github.com': jihyunjeongme
Password for 'https://jihyunjeongme@github.com':
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 15 (delta 5), reused 10 (delta 3), pack-reused 0
Unpacking objects: 100% (15/15), done.
```

### 3. Miniconda 설치 및 설정

AWS EC2에 미니콘다 다운로드

wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
![image](https://user-images.githubusercontent.com/43984584/56086834-dcdd2b00-5e99-11e9-903c-73003865f959.png)


설치 및 Conda Parh에 추가
`해당 사이트 참고` : https://openmmtools.readthedocs.io/en/latest/installation.html

$ wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
$ bash ./Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/ubuntu/miniconda3
$ export PATH="$HOME/ubuntu/miniconda3/bin:$PATH"
![image](https://user-images.githubusercontent.com/43984584/56086892-0c406780-5e9b-11e9-888a-7b536fd2d907.png)

### 4. 파이썬 가상환결 설정
conda create --name api python=3.7

![image](https://user-images.githubusercontent.com/43984584/56086904-47429b00-5e9b-11e9-92fa-558da4f560f4.png)

### 5. 가상환경 실행 시킨 후 외부프레임 워크와 라이브러리들 설치
- git clone 받은 폴더로 이동 후
- pip install -r requirements.txt


![image](https://user-images.githubusercontent.com/43984584/56086907-617c7900-5e9b-11e9-96e7-7e861db43457.png)

### 6. 아래 에러의 경우
![image](https://user-images.githubusercontent.com/43984584/56088598-212ef200-5ebf-11e9-8cb5-8929af6997e8.png)
![image](https://user-images.githubusercontent.com/43984584/56088618-5d625280-5ebf-11e9-93f9-01f1a8cb9d51.png)

서버 실행: `nohup python setup.py runserver --host=0.0.0.0 &` 후 로그확인: `vi nohup.out` 할때 해당 모듈이 없다고 하면 pip install 로 설치 해줌
할때 

실행되는 서버 확인: ps -ef | grep runserver
서버 죽이기: kill codenumber



pip install flask_script

추가로 아래 모듈이 없다고 하면 pip로 또 설치해줌

```bash
File "/home/ubuntu/python-miniter-aws/app.py", line 1, in <module>
    import bcrypt
ModuleNotFoundError: No module named 'bcrypt'
 File "setup.py", line 4, in <module>
    from app import create_app
  File "/home/ubuntu/python-miniter-aws/app.py", line 2, in <module>
    import jwt
ModuleNotFoundError: No module named 'jwt'
File "setup.py", line 4, in <module>
    from app import create_app
  File "/home/ubuntu/python-miniter-aws/app.py", line 6, in <module>
    from sqlalchemy import create_engine, text
ModuleNotFoundError: No module named 'sqlalchemy'
  File "setup.py", line 4, in <module>
    from app import create_app
  File "/home/ubuntu/python-miniter-aws/app.py", line 9, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from flask_twisted import Twisted
ModuleNotFoundError: No module named 'flask_twisted'
```
`flask_twisted' 설치 아래의 에러가 발생 할 수 있음.
```bash
Command "/home/ubuntu/ubuntu/miniconda3/envs/api/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-a0pvwfyx/Twisted/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ijf5f9bz/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-a0pvwfyx/Twisted/
```

그때 아래 커맨드 입력
sudo apt-get update
sudo apt install gcc

그리고 다시 `pip install flask-twisted` 하면 정상적으로 설치됨
```bash
 dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/ubuntu/ubuntu/miniconda3/envs/api/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/mysqlconnector.py", line 129, in dbapi
    from mysql import connector
ModuleNotFoundError: No module named 'mysql'
```
mysql시 아래 커맨드 입력
![image](https://user-images.githubusercontent.com/43984584/56088671-a961c700-5ec0-11e9-970f-7e2cc1c83241.png)


$ pip search mysql-connector | grep --color mysql-connector-python
mysql-connector-python-rf (2.2.2)        - MySQL driver written in Python
mysql-connector-python (2.0.4)           - MySQL driver written in Python

Install the mysql-connector-python-rf -

$ pip install mysql-connector-python-rf
Verify

$ python
Python 2.7.11 (default, Apr 26 2016, 13:18:56)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mysql.connector
>>>

### 7. 서버 run
서버 실행: `nohup python setup.py runserver --host=0.0.0.0 &` 후 로그확인: `vi nohup.out` 할때 
```bash
2019-04-14 05:22:35+0000 [-] Log opened.
2019-04-14 05:22:35+0000 [-] Site starting on 5000
2019-04-14 05:22:35+0000 [-] Starting factory <twisted.web.server.Site object at 0x7f77d91a0048>
```

![image](https://user-images.githubusercontent.com/43984584/56088682-e332cd80-5ec0-11e9-933d-d08200e4482b.png)

위와 같이 나오면 정상적으로 실행되는중

아래와 같이 테스트 완료
![image](https://user-images.githubusercontent.com/43984584/56088696-1bd2a700-5ec1-11e9-92a0-5b7caec34bfa.png)

**Comment by jihyunjeongme** [comment]
# EC2 Load Balancer 설정
## 1. EC2 > 로드밸런서 > 로드 밸런서 생성 > `Application Load Balancer`
![image](https://user-images.githubusercontent.com/43984584/56088708-6c4a0480-5ec1-11e9-8c40-719b3b316f31.png)

##2. 로드밸런서 구성
![image](https://user-images.githubusercontent.com/43984584/56088729-aca98280-5ec1-11e9-90db-b8cd989ea1f3.png)

## 3. 보안 그룹 구성
![image](https://user-images.githubusercontent.com/43984584/56088758-eb3f3d00-5ec1-11e9-8a49-08ab0534e588.png)

## 4. 라우팅 구성
![image](https://user-images.githubusercontent.com/43984584/56088765-0a3dcf00-5ec2-11e9-8d32-f292fdc00f79.png)

## 5. 대상 등록
![image](https://user-images.githubusercontent.com/43984584/56088778-44a76c00-5ec2-11e9-8f14-f4bb80a945c7.png)

## 6. 검토
![image](https://user-images.githubusercontent.com/43984584/56088779-5d178680-5ec2-11e9-8229-619eae56fce2.png)

![image](https://user-images.githubusercontent.com/43984584/56088788-80dacc80-5ec2-11e9-9181-08f2996a6d34.png)

![image](https://user-images.githubusercontent.com/43984584/56088810-f9418d80-5ec2-11e9-89dc-763ab8b93eaa.png)

**Comment by jihyunjeongme** [comment]
API 아키텍처 unit테스트 완료
- `python -mpytest -vv -s -p no:warnings` 

![image](https://user-images.githubusercontent.com/43984584/56092584-d03bef80-5ef8-11e9-9d2b-9df9d9164eaa.png)
